In [214]:
import torch
import numpy as np
import sys

In [2]:
torch.cuda.is_available()

True

In [41]:
x = torch.empty(2)
y = torch.empty(3, 4)
# print(x)
# print(y)
print(x, "\n", y)

tensor([1.1788e-05, 0.0000e+00]) 
 tensor([[6.3085e-33, 1.9520e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [42]:
#测试是cpu还是gpu在算
torch.tensor([1,2]).device

device(type='cpu')

In [43]:
#设置gpu为默认device
torch.set_default_device('cuda')
torch.tensor([2,3]).device

device(type='cuda', index=0)

In [47]:
#rand是0~1之间的二次分布
torch.rand(2,3)

tensor([[0.5247, 0.0479, 0.7826],
        [0.6337, 0.6519, 0.1686]], device='cuda:0')

In [48]:
#均值0方差1的二次分布
torch.randn(2,3)

tensor([[-0.4055, -1.4455,  1.0045],
        [ 0.0325,  0.0999,  0.9181]], device='cuda:0')

In [55]:
#某整数区间的二次分布
torch.randint(2,4,(2,3))

tensor([[3, 3, 2],
        [2, 2, 2]], device='cuda:0')

In [58]:
x = torch.zeros(2,3)
y = torch.ones(2,3)
x, y

(tensor([[0., 0., 0.],
         [0., 0., 0.]], device='cuda:0'),
 tensor([[1., 1., 1.],
         [1., 1., 1.]], device='cuda:0'))

In [64]:
#torch.tensor.shape是属性，tensor.size是方法，文档中放在了一起，几乎一样
x.shape, y.shape, x.size(), y.size()

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]))

In [65]:
#torch.tensor.type是方法，会显示tensor类型，而dtype则是具体的类型，参看tensor网页
x.type(), x.dtype

('torch.cuda.FloatTensor', torch.float32)

In [80]:
x = torch.ones(2,2, dtype=torch.complex64, device='cpu')
x, x.type(), x.dtype, x.device, x.size(), x.shape

(tensor([[1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j]]),
 'torch.ComplexFloatTensor',
 torch.complex64,
 device(type='cpu'),
 torch.Size([2, 2]),
 torch.Size([2, 2]))

In [71]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [81]:
torch.tensor([[1,2],[2,3]], dtype=torch.int)

tensor([[1, 2],
        [2, 3]], device='cuda:0', dtype=torch.int32)

运算

In [86]:
#torch.add和“+”原理一样
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print(x + y)
print(torch.add(x,y))

tensor([[0.1634, 0.9182],
        [0.7754, 0.2558]], device='cuda:0')
tensor([[0.1416, 0.8078],
        [0.0343, 0.8846]], device='cuda:0')
tensor([[0.3051, 1.7260],
        [0.8097, 1.1404]], device='cuda:0')
tensor([[0.3051, 1.7260],
        [0.8097, 1.1404]], device='cuda:0')


In [92]:
#在torch下，torch.add可以对‘other’进行系数调整alpha,这样操作是在torch下面，返回一个新的内存
a = torch.ones(2,3, dtype=float)
b = torch.ones(2,3, dtype=float) * 0.5
print(a)
print(b)
c = torch.add(a, b, alpha=2)
d = torch.add(a, b, alpha=1)
c,d

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)


(tensor([[2., 2., 2.],
         [2., 2., 2.]], device='cuda:0', dtype=torch.float64),
 tensor([[1.5000, 1.5000, 1.5000],
         [1.5000, 1.5000, 1.5000]], device='cuda:0', dtype=torch.float64))

In [96]:
#torch.tensor类有add和add_,add_是in-place
a = torch.ones(2,3, dtype=float)
print(a)
a.add(b)
print(a)
a.add_(b)
a


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)


tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]], device='cuda:0', dtype=torch.float64)

In [107]:
a = torch.ones(2,3,dtype=float)
b = torch.ones(2,3,dtype=float)

print(a - 0.5*b)
print(torch.sub(a,b,alpha=0.5))
print(a.sub(b,alpha=0.5))

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)


In [108]:
a = torch.ones(2,3,dtype=float)
b = torch.ones(2,3,dtype=float) * 0.5

print(a * b)
print(torch.mul(a,b))
print(a.mul(b))

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], device='cuda:0', dtype=torch.float64)


In [109]:
a = torch.ones(2,3,dtype=float)
b = torch.ones(2,3,dtype=float) * 0.5

print(a / b)
print(torch.div(a,b))
print(a.div(b))

tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)


In [126]:
#切片
x = torch.rand(5,3)
print(x)
print(x[:,1])
print(x[1,:])
print(x[1,1])
x[1,1].item()

tensor([[0.2287, 0.9232, 0.9371],
        [0.0013, 0.0935, 0.6021],
        [0.2602, 0.9186, 0.0958],
        [0.6490, 0.7521, 0.6141],
        [0.5777, 0.5047, 0.5018]], device='cuda:0')
tensor([0.9232, 0.0935, 0.9186, 0.7521, 0.5047], device='cuda:0')
tensor([0.0013, 0.0935, 0.6021], device='cuda:0')
tensor(0.0935, device='cuda:0')


0.0934663638472557

In [139]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
x.reshape(2,8), x.reshape(-1,8), x


tensor([[0.3688, 0.4549, 0.7674, 0.6319],
        [0.0536, 0.9655, 0.2839, 0.9806],
        [0.7219, 0.0072, 0.3729, 0.1005],
        [0.6671, 0.9396, 0.8792, 0.9851]], device='cuda:0')
tensor([0.3688, 0.4549, 0.7674, 0.6319, 0.0536, 0.9655, 0.2839, 0.9806, 0.7219,
        0.0072, 0.3729, 0.1005, 0.6671, 0.9396, 0.8792, 0.9851],
       device='cuda:0')


(tensor([[0.3688, 0.4549, 0.7674, 0.6319, 0.0536, 0.9655, 0.2839, 0.9806],
         [0.7219, 0.0072, 0.3729, 0.1005, 0.6671, 0.9396, 0.8792, 0.9851]],
        device='cuda:0'),
 tensor([[0.3688, 0.4549, 0.7674, 0.6319, 0.0536, 0.9655, 0.2839, 0.9806],
         [0.7219, 0.0072, 0.3729, 0.1005, 0.6671, 0.9396, 0.8792, 0.9851]],
        device='cuda:0'),
 tensor([[0.3688, 0.4549, 0.7674, 0.6319],
         [0.0536, 0.9655, 0.2839, 0.9806],
         [0.7219, 0.0072, 0.3729, 0.1005],
         [0.6671, 0.9396, 0.8792, 0.9851]], device='cuda:0'))

In [186]:
#gpu to cpu
a = torch.ones(5)
print("gpu: ", a)
print(a.device)

#转为cpu
b = a.cpu()
print("cpu: ", b)
print(b.device)

#or
c = a.to('cpu')
print("cpu: ", b)
print(c.device)

gpu:  tensor([1., 1., 1., 1., 1.], device='cuda:0')
cuda:0
cpu:  tensor([1., 1., 1., 1., 1.])
cpu
cpu:  tensor([1., 1., 1., 1., 1.])
cpu


In [193]:
#cpu to gpu
a = torch.ones(5, device='cpu')
print("gpu: ", a)
print(a.device)

#转为gpu
b = a.cuda()
print("gpu: ", b)
print(b.device)

#or
c = a.to('cuda')
# c = a.to('cuda:0')
print("gpu: ", b)
print(c.device)

gpu:  tensor([1., 1., 1., 1., 1.])
cpu
gpu:  tensor([1., 1., 1., 1., 1.], device='cuda:0')
cuda:0
gpu:  tensor([1., 1., 1., 1., 1.], device='cuda:0')
cuda:0


In [217]:
#gpu to cpu to gpu，这里默认是gpu
a = torch.ones(5)
print("gpu: ", a)

#转为cpu
a = a.cpu()
print("\n", "cpu: ", b)
print(a.device)

#转为gpu
a = a.cuda()
print("\n", "gpu: ", a)
print(a.device)

#转为numpy,numpy只能接CPU，所以要从gpu先转成cpu
a = a.cpu().numpy()
print("\n", "numpy: ", a)
print(type(a))

#转为list
a = a.tolist()
print("\n", "list: ", a)
print(type(a))

#转numpy
a = np.array(a)
print("\n", "numpy: ", a)
print(type(a))
print(id(a))

#转为cpu
b = torch.from_numpy(a)
print("\n", "cpu: ", b)
print(b.device)

c = torch.tensor(a, device='cpu')
print("\n", "cpu: ", c)
print(c.device)

print(id(b))
print(id(c))


gpu:  tensor([1., 1., 1., 1., 1.], device='cuda:0')

 cpu:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
cpu

 gpu:  tensor([1., 1., 1., 1., 1.], device='cuda:0')
cuda:0

 numpy:  [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

 list:  [1.0, 1.0, 1.0, 1.0, 1.0]
<class 'list'>

 numpy:  [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
2285532617328

 cpu:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
cpu

 cpu:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
cpu
2285532613520
2285532612272


In [219]:
#torch.from_numpy复制相同的内存地址

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [220]:
a = np.ones(5)
print(a)
b = torch.tensor(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)


In [221]:
#require_grad

a = torch.ones(5, requires_grad=True)
print(a)

tensor([1., 1., 1., 1., 1.], device='cuda:0', requires_grad=True)
